### ISSUE TITLE
Remove external Dependencies

### ISSUE THREAD

**Issue by tobiasgindler** [tracee/contextlogger#13]
Building of context information is based on a mix of ReflectionToStringBuilder and Gson.
This is suboptimal, because the produced output doesn't look very nice and is not parseable.

**Comment by SvenBunge** [comment]
@tobiasgindler is this issue still open? I think #14 fixed this issue as well.

**Comment by tobiasgindler** [comment]
Hi Sven,

da kommen noch ein paar Kleinigkeiten.

Ist aber gleich alles drin ;)

Ich schließe die dann auch gleich.

Viele Grüße

Tobias

________________________________
Tobias Gindler
Consultant

Holisticon AG


Griegstraße 75 / Haus 25


22763 Hamburg

Mobile: +49 176 1616 9026
Office: +49 40 6094 430-0
Fax:    +49 40 6094 430-30

E-Mail: tobias.gindler@holisticon.de<mailto:tobias.gindler@holisticon.de>
www.holisticon.de<http://www.holisticon.de/>

Amtsgericht Hamburg, HRB 107396
Vorstand: Oliver Ihns, Dierk Harbeck
Aufsichtsrat: Sune Nilsson (Vorsitz)

Von: Sven Bunge [mailto:notifications@github.com]
Gesendet: Freitag, 13. März 2015 12:24
An: tracee/contextlogger
Cc: Tobias Gindler
Betreff: Re: [contextlogger] Remove external Dependencies (#13)


@tobiasgindler<https://github.com/tobiasgindler> is this issue still open? I think #14<https://github.com/tracee/contextlogger/pull/14> fixed this issue as well.

**Comment by tobiasgindler** [comment]
Removed ReflectionToStringBuilder dependency
